resilience4j:
  circuitbreaker:
    configs:
      defecto:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-duration-threshold: 3s
        slow-call-rate-threshold: 50
    instances:
      products:
        base-config: defecto    
  timelimiter:
    configs:
      defecto:
        timeout-duration: 4s
    instances:
      products:
        base-config: defecto
      

spring:
  cloud:
    gateway:
      routes:
      - id: msvc-products
        uri: lb://msvc-products
        predicates:
        - Path=/api/products/**
        filters:
        - name: CircuitBreaker
          args:
            name: products
            statusCodes: 500
            fallbackUri: forward:/api/items/5
        - StripPrefix=2
        - EjemploCookie=Hola mi mensaje personalizado para productos!, user, Luis
      - id: msvc-items
        uri: lb://msvc-items
        predicates:
        - Path=/api/items/**
        filters:
        - StripPrefix=2
        - AddRequestHeader=token-request, testtoken
        - AddResponseHeader=token-response, 192923
        - AddRequestParameter=name, Luis
        - SetResponseHeader=Content-Type, text/plain