spring:
  cloud:
    gateway:
      routes:
      - id: msvc-products
        uri: lb://msvc-products
        predicates:
        - Path=/api/products/**
        filters:
        - StripPrefix=2
        - EjemploCookie=Hola mi mensaje personalizado para productos!, user, Luis
        #- name: SampleCookie
        #  args:
        #    message: Hola mi mensaje personalizado para productos!
        #    name: user
        #    value: Luis
      - id: msvc-items
        uri: lb://msvc-items
        predicates:
        - Path=/api/items/**
        filters:
        - StripPrefix=2
        - AddRequestHeader=token-request, testtoken
        - AddResponseHeader=token-response, 192923
        - AddRequestParameter=name, Luis
        - SetResponseHeader=Content-Type, text/plain